### ISSUE TITLE
Use last submitted gas parameter if API fails

### ISSUE THREAD

**Issue by lwYeo** [lwYeo/SoliditySHA3Miner#8]
As described in the title, below is the related error message.
Currently, it will take the minimum value from gasToMine parameter, which can be undesirable at times.
```
[2018-11-25T09:23:31] [ERROR] Failed to read gas price from API: https://ethgasstation.info/json/ethgasAPI.json
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at SoliditySHA3Miner.Utils.Json.DeserializeFromURL(String url)
   at SoliditySHA3Miner.NetworkInterface.Web3Interface.SubmitSolution(String address, Byte[] digest, Byte[] challenge, UInt64 difficulty, Byte[] nonce, IMiner sender)
```

**Comment by lwYeo** [comment]
Issue will be closed in the next bugfix version release.
